Numpy Practice

In [2]:
import numpy as np

print(np.__version__)

1.24.3


In [3]:
arr=np.array(10)
arr

array(10)

In [4]:
arr=np.array([10,11])
print (arr)

[10 11]


In [5]:
arr=np.array([[10,11],[12,13]])
print(arr)

[[10 11]
 [12 13]]


Arrays in numpy with all dimensions

In [6]:
import numpy as np

print(np.array(10) )# 0D

print(np.array([1,2])) # 1D

print(np.array([[1,2],[3,4]])) # 2D

print(np.array([  [  [1,2],[3,4]  ]  ,  [   [5,6],[7,8]  ]  ])) # 3D


10
[1 2]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ndmin=5

In [7]:
arr = np.array([[[1,2,3,4,5]],[[6,7,8,9,10]],[[6,7,8,9,10]]])
print(arr)
# print(arr.ndim)
print(arr.shape)

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[ 6  7  8  9 10]]]
(3, 1, 5)


filling arrays with auto elements

In [14]:
import numpy as np

arr = np.zeros((3,1,5))
print(arr)

[[[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]]


In [13]:
arr=np.ones((4,8,3))
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [10]:
arr= np.arange(10,21,3)
print(arr)

[10 13 16 19]


Sorting Arrays

In [11]:
arr= np.array([2,1,5,6,3,8,7,4])

sorted_array= np.sort(arr)
print(sorted_array)


[1 2 3 4 5 6 7 8]


Sort alphabets or names

In [12]:
arr= np.array(["Apple","Zebra","Tea"])

sorted_array= np.sort(arr)
print(sorted_array)


['Apple' 'Tea' 'Zebra']


Sorting 2d array

In [18]:
arr=np.array([[6,2,3],[9,5,6]])
print( np.sort(arr)  )

[[2 3 6]
 [5 6 9]]


In [41]:
arr= np.array([50,20,300,40,-5,65,70,85])

print(arr[0:2])


[50 20]


In [47]:
mat=np.array([[10,20,21,22,25],[30,40,41,42,43]])
print(mat)
print(mat[1,2])

[[10 20 21 22 25]
 [30 40 41 42 43]]
41


In [86]:
mat=np.array([  [[21,22,25],[41,42,43]]  , [[50,51,52],[60,61,62]]  ])
print(mat)
print("Value:",mat[1,1,2])


[[[21 22 25]
  [41 42 43]]

 [[50 51 52]
  [60 61 62]]]
Value: 62
[61 62]


In [81]:
arr=np.array([1,2,3,4,5,6])

print(arr[1:5:1])

[2 3 4 5]


In [82]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr[1,1:4])

[6 7 8]


In [87]:
arr=np.array([2,50,40,60,70,40])

val=np.where(arr==40)

print(val)


(array([2, 5], dtype=int64),)


In [92]:
arr=np.array([1,2,3,4,5])

val=np.where(arr%3==0)

print(val)

(array([2], dtype=int64),)


In [97]:
arr=np.array([10,20,50,60])

val=np.searchsorted(arr,[-10,40,55])
val

array([0, 2, 3], dtype=int64)

reshape array   

In [102]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
rs=arr.reshape(4,3)
rs

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [100]:
arr=np.array([[1,2,],[3,4]])
print(arr.reshape(-1))

[1 2 3 4]
