Numpy Practice

In [2]:
import numpy as np

print(np.__version__)

1.24.2


In [3]:
arr=np.array(10)
arr

array(10)

In [4]:
arr=np.array([10,11])
print (arr)

[10 11]


In [5]:
arr=np.array([[10,11],[12,13]])
print(arr)

[[10 11]
 [12 13]]


Arrays in numpy with all dimensions

In [6]:
import numpy as np

print(np.array(10) )# 0D

print(np.array([1,2])) # 1D

print(np.array([[1,2],[3,4]])) # 2D

print(np.array([  [  [1,2],[3,4]  ]  ,  [   [5,6],[7,8]  ]  ])) # 3D


10
[1 2]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ndmin=5

In [7]:
arr = np.array([[[1,2,3,4,5]],[[6,7,8,9,10]],[[6,7,8,9,10]]])
print(arr)
# print(arr.ndim)
print(arr.shape)

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[ 6  7  8  9 10]]]
(3, 1, 5)


filling arrays with auto elements

In [8]:
import numpy as np

arr = np.zeros((3,1,5))
print(arr)

[[[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]]


In [9]:
arr=np.ones((4,8,3))
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [10]:
arr= np.arange(10,21,3)
print(arr)

[10 13 16 19]


Sorting Arrays

In [11]:
arr= np.array([2,1,5,6,3,8,7,4])

sorted_array= np.sort(arr)
print(sorted_array)


[1 2 3 4 5 6 7 8]


Sort alphabets or names

In [12]:
arr= np.array(["Apple","Zebra","Tea"])

sorted_array= np.sort(arr)
print(sorted_array)


['Apple' 'Tea' 'Zebra']


Sorting 2d array

In [13]:
arr=np.array([[6,2,3],[9,5,6]])
print( np.sort(arr)  )

[[2 3 6]
 [5 6 9]]


In [14]:
arr= np.array([50,20,300,40,-5,65,70,85])

print(arr[0:2])


[50 20]


In [15]:
mat=np.array([[10,20,21,22,25],[30,40,41,42,43]])
print(mat)
print(mat[1,2])

[[10 20 21 22 25]
 [30 40 41 42 43]]
41


In [16]:
mat=np.array([  [[21,22,25],[41,42,43]]  , [[50,51,52],[60,61,62]]  ])
print(mat)
print("Value:",mat[1,1,2])


[[[21 22 25]
  [41 42 43]]

 [[50 51 52]
  [60 61 62]]]
Value: 62


In [17]:
arr=np.array([1,2,3,4,5,6])

print(arr[1:5:1])

[2 3 4 5]


In [18]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr[1,1:4])

[6 7 8]


In [19]:
arr=np.array([2,50,40,60,70,40])

val=np.where(arr==40)

print(val)


(array([2, 5], dtype=int64),)


In [20]:
arr=np.array([1,2,3,4,5])

val=np.where(arr%3==0)

print(val)

(array([2], dtype=int64),)


In [21]:
arr=np.array([10,20,50,60])

val=np.searchsorted(arr,[-10,40,55])
val

array([0, 2, 3], dtype=int64)

reshape array   

In [22]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
rs=arr.reshape(4,3)
rs

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
arr=np.array([[1,2,],[3,4]])
print(arr.reshape(-1))

[1 2 3 4]


numpy filter

In [24]:
import numpy as np
arr = np.array([10,30,20,60,70])
b= [True,False,False,False,True]
newarr = arr[b]
print(newarr)

[10 70]


In [25]:
arr= np.array([0,1,2,3,5,8,13])
result = filter(lambda input:input%2!=0,arr)
print(list(result))

[1, 3, 5, 13]


In [26]:
arr= np.array([0,1,2,3,5,8,13])
result = filter(lambda input:input%2==0,arr)
print(list(result))

[0, 2, 8]


In [27]:
a=np.arange(6).reshape(2,3)
print("A:",a)

b=np.arange(5,11).reshape(2,3)
print("B:",b)


c=np.concatenate((a,b))
print("Concatenated:",c)


A: [[0 1 2]
 [3 4 5]]
B: [[ 5  6  7]
 [ 8  9 10]]
Concatenated: [[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]


In [28]:
a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)

mat=np.concatenate((a,b),axis=1)
print(mat)


[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [29]:
stack_mat = np.stack((a,b),axis=2)
stack_mat

array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])

In [30]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
np.hstack((a,b))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [32]:
mat= np.dstack((a,b))
print(mat[1,1,1])
print(mat)

10
[[[ 0  6]
  [ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]
  [ 5 11]]]


PANDAS

In [33]:
import pandas as pd
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,100])
s=pd.Series(a)
s

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int32

In [34]:
s=pd.Series(a,index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
s['i']

90

In [35]:
l1=[1,2,3,4]

a=pd.Series(l1)
a


0    1
1    2
2    3
3    4
dtype: int64

In [36]:
import pandas as pd

list1=[10,20,30,40,[50,60]]
df = pd.DataFrame(data=list1)
print(df)
def healthstatus(bmi):
    if (bmi < 18.5):
        print("underweight")
  
    elif (bmi >= 18.5 and bmi < 24.9):
        print("Healthy")
  
    elif (bmi >= 24.9 and bmi < 30):
        print( "overweight")
  
    elif (bmi >= 30):
        print("Suffering from Obesity")
  

          0
0        10
1        20
2        30
3        40
4  [50, 60]


In [37]:
import pandas as pd

bmi={ "age":[22,23,21,24,23],"gender":["M","F","M","F","M"],"height":[161,164,166,170,169],"weight":[65,66,68,71,74] }

df=pd.DataFrame(bmi)
# print(df)
def healthstatus(bmi):
    status=""
    if (bmi < 18.5):
        print("underweight")
        status="UnderWeight"
        return status
  
    elif (bmi >= 18.5 and bmi < 24.9):
        print("Healthy")
        status="Healthy"
        return status
  
  
    elif (bmi >= 24.9 and bmi < 30):
        print( "overweight")
        status="overweight"
        return status
  
    elif (bmi >= 30):
        print("Suffering from Obesity")
        status="Suffering from Obesity"
        return status
  
bmivalues=[]
healthstatuses=[]
for i in range(1):
    ht=bmi["height"]
    wt=bmi["weight"]
    
    for j in range(len(ht)):
        # print(ht[j])
        # print(wt[j])
        ans=wt[j]/(ht[j]/100)**2
        print(ans)
        bmivalues.append(ans)
        bmistate=healthstatus(ans)
        healthstatuses.append(bmistate)

df["BMI Values"]=bmivalues
df["Your Health Status"]=healthstatuses
df

25.076193048107708
overweight
24.538964901844146
Healthy
24.677021338365513
Healthy
24.56747404844291
Healthy
25.909456951787405
overweight


age gender  height  weight  BMI Values Your Health Status
0   22      M     161      65   25.076193         overweight
1   23      F     164      66   24.538965            Healthy
2   21      M     166      68   24.677021            Healthy
3   24      F     170      71   24.567474            Healthy
4   23      M     169      74   25.909457         overweight

In [38]:
import pandas as pd

bmi={ "age":[22,23,21,24,23],"gender":["M","F","M","F","M"],"height":[161,164,166,170,169],"weight":[65,66,68,71,74] }

df=pd.DataFrame(bmi)
for i in range(5):
    a=df.loc[1]
    print(a)


age        23
gender      F
height    164
weight     66
Name: 1, dtype: object
age        23
gender      F
height    164
weight     66
Name: 1, dtype: object
age        23
gender      F
height    164
weight     66
Name: 1, dtype: object
age        23
gender      F
height    164
weight     66
Name: 1, dtype: object
age        23
gender      F
height    164
weight     66
Name: 1, dtype: object


In [39]:
import pandas as pd

df=pd.read_json("data.json")
print(df.to_string)


<bound method DataFrame.to_string of                                                    students
student1  {'name': 'ABC', 'rollnumber': 1, 'class': 1, '...
student2       {'name': 'DEF', 'rollnumber': 2, 'class': 2}
student3       {'name': 'EFG', 'rollnumber': 3, 'class': 3}>
