Numpy Practice

In [1]:
import numpy as np

print(np.__version__)

1.24.3


In [4]:
arr=np.array(10)
arr

array(10)

In [8]:
arr=np.array([10,11])
print (arr)

[10 11]


In [10]:
arr=np.array([[10,11],[12,13]])
print(arr)

[[10 11]
 [12 13]]


Arrays in numpy with all dimensions

In [12]:
import numpy as np

print(np.array(10) )# 0D

print(np.array([1,2])) # 1D

print(np.array([[1,2],[3,4]])) # 2D

print(np.array([  [  [1,2],[3,4]  ]  ,  [   [5,6],[7,8]  ]  ])) # 3D


10
[1 2]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ndmin=5

In [31]:
arr = np.array([[[1,2,3,4,5]],[[6,7,8,9,10]],[[6,7,8,9,10]]])
print(arr)
# print(arr.ndim)
print(arr.shape)

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[ 6  7  8  9 10]]]
(3, 1, 5)


filling arrays with auto elements

In [33]:
import numpy as np

arr = np.zeros(4)
print(arr)

[0. 0. 0. 0.]


In [38]:
arr=np.ones((50,50))
print(arr)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [43]:
arr= np.arange(10,21,3)
print(arr)

[10 13 16 19]


Sorting Arrays

In [44]:
arr= np.array([2,1,5,6,3,8,7,4])

sorted_array= np.sort(arr)
print(sorted_array)


[1 2 3 4 5 6 7 8]


Sort alphabets or names

In [45]:
arr= np.array(["Apple","Zebra","Tea"])

sorted_array= np.sort(arr)
print(sorted_array)


['Apple' 'Tea' 'Zebra']
