In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from keras.models import Sequential
from keras.layers import Dense
import cv2
import numpy as np
# Load Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create the SVM model using SVC from scikit-learn
svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)

# Evaluate the SVM model
accuracy = svm_model.score(X_test, y_test)
print("SVM accuracy:", accuracy)

# Alternatively, you can use Keras to build an SVM-like model
model = Sequential()
model.add(Dense(1, input_dim=4, activation='linear'))
model.compile(optimizer='adam', loss='hinge', metrics=['accuracy'])

# Train the SVM-like model
model.fit(X_train, y_train, epochs=10, batch_size=32)

# Evaluate the SVM-like model
_, accuracy = model.evaluate(X_test, y_test)
print("SVM-like model accuracy:", accuracy)




SVM accuracy: 1.0
Epoch 1/10
4/4 [==============================] - 1s 10ms/step - loss: 4.3346 - accuracy: 0.3333
Epoch 2/10
4/4 [==============================] - 0s 6ms/step - loss: 4.2683 - accuracy: 0.3333
Epoch 3/10
4/4 [==============================] - 0s 6ms/step - loss: 4.2017 - accuracy: 0.3333
Epoch 4/10
4/4 [==============================] - 0s 6ms/step - loss: 4.1328 - accuracy: 0.3333
Epoch 5/10
4/4 [==============================] - 0s 6ms/step - loss: 4.0680 - accuracy: 0.3333
Epoch 6/10
4/4 [==============================] - 0s 9ms/step - loss: 4.0006 - accuracy: 0.3333
Epoch 7/10
4/4 [==============================] - 0s 7ms/step - loss: 3.9334 - accuracy: 0.3333
Epoch 8/10
4/4 [==============================] - 0s 12ms/step - loss: 3.8663 - accuracy: 0.3333
Epoch 9/10
4/4 [==============================] - 0s 8ms/step - loss: 3.7979 - accuracy: 0.3333
Epoch 10/10
1/1 [==============================] - 1s 1s/step - loss: 3.8828 - accuracy: 0.3333
SVM-like model accur

In [7]:
import numpy as np
from keras.utils import to_categorical

# Example categorical labels
labels = ['1','2','3','4','5']

# Perform one-hot encoding
encoded_labels = to_categorical(labels,num_classes=None)

print(encoded_labels)


[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [8]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.optimizers import Adam
from keras import utils
from keras.layers import Conv2D
from keras.layers import MaxPooling2D

#reshape in form of (60000, 28, 28, 1)
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], X_train.shape[2], 1).astype('float32')
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], X_test.shape[2], 1).astype('float32')
#normalize to get data in range of 0-1
X_train/=255
X_test/=255
number_of_classes = 10
y_train = utils.to_categorical(y_train, number_of_classes)
y_test = utils.to_categorical(y_test, number_of_classes)


model = Sequential()
model.add(Conv2D(32, (5, 5), input_shape=(X_train.shape[1], X_train.shape[2], 1), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(number_of_classes, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])

model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=5, batch_size=200)

import cv2
img = cv2.imread('C:/Users/Nextingo/Desktop/1.png', cv2.IMREAD_GRAYSCALE)
# resize image
resized = cv2.resize(img, (28,28), interpolation = cv2.INTER_AREA)
img = np.resize(resized, (28,28,1))
im2arr = np.array(img)
im2arr = im2arr.reshape(1,28,28,1)
y_pred = model.predict_classes(im2arr)
print(y_pred)


IndexError: tuple index out of range

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import LSTM, Dense

# Generate synthetic timeseries data
def generate_timeseries_data(n_steps):
    time = np.linspace(0, 2*np.pi, n_steps)
    data = np.sin(time) + np.random.normal(0, 0.1, n_steps)
    return data

n_steps = 100
data = generate_timeseries_data(n_steps)

# Prepare data for LSTM (input and target)
X = data[:-1]
y = data[1:]

# Reshape data for LSTM (samples, timesteps, features)
X = X.reshape(-1, 1, 1)

# Create LSTM model
model = Sequential()
model.add(LSTM(32, input_shape=(1, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Train the model
model.fit(X, y, epochs=100, batch_size=1)

# Generate test data for evaluation
test_data = generate_timeseries_data(n_steps)

# Prepare test data for LSTM (input and target)
X_test = test_data[:-1]
y_test = test_data[1:]

# Reshape test data for LSTM (samples, timesteps, features)
X_test = X_test.reshape(-1, 1, 1)

# Evaluate the model on test data
loss = model.evaluate(X_test, y_test, verbose=0)
print("Test loss:", loss)

# Make predictions using the trained model
predictions = model.predict(X_test)

# Plot the true values and the predictions
plt.figure(figsize=(10, 6))
plt.plot(y_test, label='True Values')
plt.plot(predictions, label='Predictions', linestyle='dashed')
plt.legend()
plt.title('Timeseries Prediction using Keras LSTM')
plt.xlabel('Time Steps')
plt.ylabel('Value')
plt.show()
